version: '3.8'


services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: arun
      POSTGRES_PASSWORD: Arun@123
      POSTGRES_DB: tweet
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: arun@reontel.com
      PGADMIN_DEFAULT_PASSWORD: Arun@123
    ports:
      - "8080:80"
    depends_on:
      - postgres


volumes:
  postgres-data:

